kind: Deployment
apiVersion: apps/v1
metadata:
  name: caikit-embeddings
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: caikit-embeddings
  template:
    metadata:
      labels:
        deployment: caikit-embeddings
    spec:
      volumes:
        - name: cos-pvc
          persistentVolumeClaim:
            claimName: pvc-caikit-embeddings-cos
        - name: tls-secret
          secret:
            secretName: tls-secret
            defaultMode: 420
      containers:
        - resources:
            limits:
              nvidia.com/gpu: '1'
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - bash
            - '-c'
            - >-
              cd deployment/assets/ && python create-script.py && cd ../../ &&
              sh load-models-config.sh && cd demo/server && python
              start_runtime.py
          env:
            - name: TRANSFORMERS_CACHE
              value: /opt/app-root/src/.cache/huggingface/hub/
            - name: HUGGINGFACE_HUB_CACHE
              value: $(TRANSFORMERS_CACHE)
            - name: MODELS_DIR
              value: '["sentence-transformers_all-MiniLM-L6-v2","slate.rtvr271M"]'
            - name: MODELS_LIST
              value: '["mini", "slate"]'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: cos-pvc
              mountPath: /opt/app-root/src/.cache/huggingface/sentence_transformers/
              subPath: models/
            - name: cos-pvc
              mountPath: /opt/app-root/src/.cache/huggingface/hub/
              subPath: transformers_cache/
            - name: cos-pvc
              mountPath: /opt/app-root/src/demo/models/
            - name: tls-secret
              mountPath: /mnt
          terminationMessagePolicy: File
          image: 'icr.io/fm-stack/caikit-embeddings:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: icr-caikit-image
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Secret
apiVersion: v1
metadata:
  name: icr-caikit-image
data:
  .dockerconfigjson: <base64 encoded dockerconfigjson>
type: kubernetes.io/dockerconfigjson
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: caikit-embeddings-route
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: >-
    caikit-embeddings-route-<oc-project-name>.<cluster-host>.<cluster-domain>
  to:
    kind: Service
    name: caikit-embeddings-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: passthrough
---
apiVersion: v1
kind: Service
metadata:
  name: caikit-embeddings-service
spec:
  selector:
    deployment: caikit-embeddings
  ports:
    - name: server-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc-port
      protocol: TCP
      port: 8085
      targetPort: 8085

